#name: Deploy to Cloud Run
#on:
#  push:
#    branches:
#      - main
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    environment: prod
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v2
#
#      - name: Set up GCP SDK
#        uses: google-github-actions/setup-gcloud@v1
#        with:
#          project_id: ${{ secrets.GCP_PROJECT_ID }}
#          service_account_key: ${{ secrets.GCP_SA_KEY }}
#
#      - name : Authenticate Docker with GCP
#        run: gcloud auth configure-docker
#
#      - name : Build Docker Image
#        run: |
#          docker build . -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/customer:latest
#          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/customer:latest
#
#      - name: Deploy to Cloud Run
##        run: |
##          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE_NAME }} \
##          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/customer:latest \
##          --add-cloudsql-instances windy-anchor-432416-e8:europe-west1:studi\
##          --update-env-vars DB_HOST=/cloudsql/windy-anchor-432416-e8:europe-west1:studi, DB_USER=root,DB_PASS=Mfarej860!,DB_NAME=jpa \
##          --platform managed \
##          --region
##          --allow-unauthenticated \
##          --service-account ${{ secrets.GCP_SERVICE_ACCOUNT }}
#        run: |
#          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE_NAME }} \
#          --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/customer:latest \
#          --add-cloudsql-instances jeux-olym-433811:us-central1:jpa\
#          --update-env-vars DB_HOST=/cloudsql/jeux-olym-433811:us-central1:jpa, DB_USER=root,DB_PASS=Mfarej860!,DB_NAME=jpa \
#          --platform managed \
#          --region us-central1 \
#          --allow-unauthenticated \
#          --timeout=300 \
#          --service-account ${{ secrets.GCP_SERVICE_ACCOUNT }}

#name: Deploy to Cloud Run
#on:
#  push:
#    branches: [ main ]
#
#jobs:
#  deploy:
#    runs-on: ubuntu-latest
#    environment: prod
#
#    steps:
#      - name: Checkout code
#        uses: actions/checkout@v4
#
#      - name: Set up GCP SDK
#        uses: google-github-actions/setup-gcloud@v2
#        with:
#          project_id: ${{ secrets.GCP_PROJECT_ID }}
#          service_account_key: ${{ secrets.GCP_SA_KEY }}
#          export_default_credentials: true
#
#      - name: Authenticate Docker with GCP
#        run: gcloud auth configure-docker gcr.io
#
#      - name: Build Docker Image
#        run: |
#          docker build . -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/customer:latest
#          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/customer:latest
#
#      - name: Deploy to Cloud Run
#        run: |
#          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE_NAME }} \
#            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/customer:latest \
#            --platform managed \
#            --region us-central1 \
#            --allow-unauthenticated \
#            --service-account ${{ secrets.GCP_SERVICE_ACCOUNT }} \
#            --add-cloudsql-instances jeux-olym-433811:us-central1:jpa \
#            --timeout=300
#
#      - name: Show service URL
#        run: gcloud run services describe ${{ secrets.CLOUD_RUN_SERVICE_NAME }} --region us-central1 --format='value(status.url)'
name: Deploy to Cloud Run (NO-DB test)

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Auth Docker for gcr.io
        run: gcloud auth configure-docker gcr.io

      - name: Build & Push image
        env:
          IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/customer:${{ github.sha }}
        run: |
          docker build -t "$IMAGE" .
          docker push "$IMAGE"

      - name: Deploy to Cloud Run (DB auto-config DISABLED)
        env:
          IMAGE: gcr.io/${{ secrets.GCP_PROJECT_ID }}/customer:${{ github.sha }}
        run: |
          gcloud run deploy ${{ secrets.CLOUD_RUN_SERVICE_NAME }} \
            --image "$IMAGE" \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --service-account ${{ secrets.GCP_SERVICE_ACCOUNT }} \
            --timeout=300 \
            --set-env-vars SPRING_AUTOCONFIGURE_EXCLUDE=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration

      - name: Show service URL
        run: gcloud run services describe ${{ secrets.CLOUD_RUN_SERVICE_NAME }} --region us-central1 --format='value(status.url)'
